# Done to increase the memory available to gradle
org.gradle.jvmargs=-Xmx3G
# Enable Gradle configuration cache
org.gradle.configuration-cache=true
# enable the remote build cache
org.gradle.caching=true

# Metadata
mod_id=starfinder
mod_description=Template Mod.
mod_display_name=Starfinder
sources_url=https://github.com/CammiePone/Starfinder
issues_url=https://github.com/CammiePone/Starfinder/issues
license_url=https://github.com/CammiePone/Starfinder/blob/HEAD/LICENSE.md
discord_url=https://cammiescorner.dev/discord
homepage_url=https://github.com/CammiePone/Starfinder

# Publishing
maven_group_id=dev.cammiescorner.starfinder
curseforge_id=0
modrinth_id=0
